import { Comic_Neue } from "next/font/google";
import "./globals.css";
import BackgroundZoom from "@/components/BackgroundZoom";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const comicFont = Comic_Neue({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-comic",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${comicFont.variable} antialiased relative min-h-screen overflow-x-hidden flex flex-col`}
        style={{ fontFamily: 'var(--font-comic), cursive' }}
      >
        {/* Background with Zoom Effect */}
        <BackgroundZoom />

        {/* Header */}
        <Header />

        {/* Main Content */}
        <main className="relative z-10 ">
          {children}
        </main>

        {/* Footer */}
        <Footer />
      </body>
    </html>
  );
}
