import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BackgroundZoom from "@/components/BackgroundZoom";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative min-h-screen overflow-x-hidden`}
      >
        {/* Background with Zoom Effect */}
        <BackgroundZoom />

        {/* Main Content */}
        <main className="relative z-10 px-4 sm:px-6 md:px-8 lg:px-12">
          {children}
        </main>
      </body>
    </html>
  );
}
